### ISSUE TITLE
i tried style50 on my mac. I've done all the setting up, but this happen. How do i fix this?

### ISSUE THREAD

**Issue by alexander-code-bit** [cs50/style50#103]
$ style50 hello.c
Traceback (most recent call last):
  File "/usr/local/bin/style50", line 5, in <module>
    from style50.__main__ import main
  File "/usr/local/lib/python3.10/site-packages/style50/__init__.py", line 20, in <module>
    from ._api import Style50, StyleCheck, Error
  File "/usr/local/lib/python3.10/site-packages/style50/_api.py", line 21, in <module>
    from . import __version__, renderer
  File "/usr/local/lib/python3.10/site-packages/style50/renderer/__init__.py", line 1, in <module>
    from ._renderers import to_ansi, to_html, to_json, to_ansi_score
  File "/usr/local/lib/python3.10/site-packages/style50/renderer/_renderers.py", line 4, in <module>
    import jinja2
  File "/usr/local/lib/python3.10/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.10/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.10/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.10/site-packages/markupsafe/__init__.py)

**Comment by rongxin-liu** [comment]
Try running this command and see if it fixes the issue:
```
pip3 install style50 --upgrade
```

Alternatively, please install `markupsafe==2.0.1` by running:
```
pip3 install markupsafe==2.0.1
```
