### ISSUE TITLE
ImportError: failed to find libmagic.  Check your installation

### ISSUE THREAD

**Issue by luka-teodor** [cs50/style50#124]
Hi, the following error occurred after running style50

Traceback (most recent call last):
  File "/Users/u/Programming/project1/.venv/bin/style50", line 5, in <module>
    from style50.__main__ import main
  File "/Users/u/Programming/project1/.venv/lib/python3.9/site-packages/style50/__init__.py", line 17, in <module>
    from ._api import Style50, StyleCheck, Error
  File "/Users/u/Programming/project1/.venv/lib/python3.9/site-packages/style50/_api.py", line 18, in <module>
    import magic
  File "/Users/u/Programming/project1/.venv/lib/python3.9/site-packages/magic/__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
  File "/Users/u/Programming/project1/.venv/lib/python3.9/site-packages/magic/loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
    
   macOS Monterey 12.7.4
   Python 3.9.6

Maybe it's an issue with the magic package, but style50 is not working at all

**Comment by luka-teodor** [comment]
fixed, just needed to install libmagic

`brew install libmagic`

**Comment by luka-teodor** [comment]
fixed, just needed to install libmagic

`brew install libmagic`
