### ISSUE TITLE
catch errors when style50 fails parsing because of the file's C syntax

### ISSUE THREAD

**Issue by tobiasbueschel** [cs50/style50#18]
The following code will break because it's not correct C syntax. Even though, clang will warn about this, style50 should also handle this exception.

```c
int main(void)
{
    int n = 1;
    switch (n) // hello
    {
        case 1
        case 2:
            break;
        case 3:
        default:
            break;
    }

    return 0;
}
```

Failed to parse ../tests/issue9.c.
Exception in thread "main" java.lang.NullPointerException
       	at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:64)
       	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:49)
       	at c.CMain.lint_C(CMain.java:106)
       	at StyleMain.main(StyleMain.java:175)

**Comment by tobiasbueschel** [comment]
This has been fixed by the resolution for https://github.com/cs50/style50/issues/24

In theory, if **style50** encounters incorrect C syntax, it will provide the following error message.
```
Failed to parse ../tests/issues/issue18.c.
Could not run style50 on ../tests/issues/issue18.c.
```

However, in practice, **clang always runs before style50** and thus the program would never show above error message but rather clang's output.

In this case, the following message:
```bash
../tests/issues/issue18.c:6:15: error: expected ':' after 'case'
        case 1
              ^
              :
fix-it:"../tests/issues/issue18.c":{6:15-6:15}:":"
```

or the JSON response with the -d flag:

```json
{"../tests/issues/issue18.c": [{
    "col": "15",
    "code": "        case 1\n              ^",
    "level": "error",
    "line": "6",
    "message": "expected ':' after 'case'"
}]}
```
