### ISSUE TITLE
Cannot find module 'express'

### ISSUE THREAD

**Issue by dmalan** [cs50/style50#31]
```
cd dist/server
docker-compose build
docker-compose up
docker exec -it style50_web bash -l # in a separate terminal window
```

**Comment by tobiasbueschel** [comment]
I started the Docker container and then executed `make jar` to create `style50.jar`

When I tried to run it, I received the following error:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: c/utils/CTokenFactory : Unsupported major.minor version 52.0
       	at java.lang.ClassLoader.defineClass1(Native Method)
       	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
       	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
       	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
       	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
       	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
       	at java.security.AccessController.doPrivileged(Native Method)
       	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
       	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
       	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
       	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
       	at c.CMain.<init>(CMain.java:70)
       	at Style50.runStyle50(Style50.java:156)
       	at Style50.parseFiles(Style50.java:139)
       	at Style50.main(Style50.java:206)
```

Luckily, I was able to fix it with the following [source](http://stackoverflow.com/a/8448497/5237070):
```sudo update-alternatives --config java```

Running `node app.js` starts the Node.js server as expected!

With that said, I changed the port for the Node.js server to `5000`. The Docker and the Node.js server both had `8080` before.
