### ISSUE TITLE
Error when run in a git repo

### ISSUE THREAD

**Issue by brianyu28** [cs50/style50#45]
If in git repo, running `style50 --verbose .` with v2.3.0 yields:

```python

...

::::::::::::::
./.git/index
::::::::::::::
Sorry, something's wrong! Let sysadmins@cs50.harvard.edu know!
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.6.0/bin/style50", line 11, in <module>
    load_entry_point('style50==2.3.0', 'console_scripts', 'style50')()
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/style50/__main__.py", line 65, in main
    Style50(main.args.file, output=main.args.output).run()
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/style50/style50.py", line 101, in run_diff
    results = self._check(file)
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/style50/style50.py", line 195, in _check
    return check(f.read())
  File "/opt/pyenv/versions/3.6.0/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 13: invalid continuation byte
```

**Comment by cmlsharp** [comment]
@49
