### ISSUE TITLE
after installing on macOS, style50 errs with "failed to find libmagic"

### ISSUE THREAD

**Issue by dmalan** [cs50/style50#84]
```
$ sudo pip3 install style50
Collecting style50
  Downloading https://files.pythonhosted.org/packages/24/7c/865e9aa2f714bc05986df687195696df21f865e6c099a4138bd11fff7ac0/style50-2.6.4.tar.gz
Collecting argparse (from style50)
  Downloading https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Collecting autopep8>=1.3.3 (from style50)
  Downloading https://files.pythonhosted.org/packages/45/f3/24b437da561b6af4840c871fbbda32889ca304fc1f7b6cc3ada8b09f394a/autopep8-1.4.4.tar.gz (114kB)
    100% |████████████████████████████████| 122kB 7.2MB/s 
Collecting icdiff (from style50)
  Downloading https://files.pythonhosted.org/packages/8f/7d/a6ae9d58faa076bda8930c167204cac14d44941cba60c2642e2f4aac6c44/icdiff-1.9.1.tar.gz
Collecting jsbeautifier (from style50)
  Downloading https://files.pythonhosted.org/packages/0f/e6/83b91849db130583d321e13c1d183bf38b86cd487dab979478d3087412a6/jsbeautifier-1.10.0.tar.gz (69kB)
    100% |████████████████████████████████| 71kB 25.3MB/s 
Collecting python-magic (from style50)
  Downloading https://files.pythonhosted.org/packages/42/a1/76d30c79992e3750dac6790ce16f056f870d368ba142f83f75f694d93001/python_magic-0.4.15-py2.py3-none-any.whl
Collecting termcolor (from style50)
  Downloading https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
Collecting pycodestyle>=2.4.0 (from autopep8>=1.3.3->style50)
  Downloading https://files.pythonhosted.org/packages/0e/0c/04a353e104d2f324f8ee5f4b32012618c1c86dd79e52a433b64fceed511b/pycodestyle-2.5.0-py2.py3-none-any.whl (51kB)
    100% |████████████████████████████████| 51kB 13.1MB/s 
Collecting six>=1.6.1 (from jsbeautifier->style50)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting editorconfig>=0.12.0 (from jsbeautifier->style50)
  Downloading https://files.pythonhosted.org/packages/2e/7a/aedb7e1cba1778c1d78c4f6ad88d4b0dfca6b991befa248164121091d911/EditorConfig-0.12.2.tar.gz
Installing collected packages: argparse, pycodestyle, autopep8, icdiff, six, editorconfig, jsbeautifier, python-magic, termcolor, style50
  Running setup.py install for autopep8 ... done
s  Running setup.py install for icdiff ... done
  Running setup.py install for editorconfig ... done
ty  Running setup.py install for jsbeautifier ... \done
  Running setup.py install for termcolor ... \^R
stdone
  Running setup.py install for style50 ... done
Successfully installed argparse-1.4.0 autopep8-1.4.4 editorconfig-0.12.2 icdiff-1.9.1 jsbeautifier-1.10.0 pycodestyle-2.5.0 python-magic-0.4.15 six-1.12.0 style50-2.6.4 termcolor-1.1.0

$ style50 cli50/__main__.py 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/style50", line 11, in <module>
    load_entry_point('style50==2.6.4', 'console_scripts', 'style50')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/style50/__init__.py", line 20, in <module>
    from ._api import Style50, StyleCheck, Error
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/style50/_api.py", line 17, in <module>
    import magic
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

**Comment by Furtim** [comment]
Hi,  style50 version  2.7.4 still exhibiting same on OSX Catalina.

`❯ style50             
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/style50", line 11, in <module>
    load_entry_point('style50==2.7.4', 'console_scripts', 'style50')()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/style50/__init__.py", line 20, in <module>
    from ._api import Style50, StyleCheck, Error
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/style50/_api.py", line 18, in <module>
    import magic
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/magic.py", line 201, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation`

pip install libmagic does not fix.

**Comment by alexhernandez** [comment]
After running both:
`pip3 install style50`
`pip3 install --upgrade style50`

I get a slightly different error output but similar issue:

```
alexhernandez - (cs50/problems/2020/x/mario/less) $ style50
Traceback (most recent call last):
  File "/usr/local/bin/style50", line 5, in <module>
    from style50.__main__ import main
  File "/usr/local/lib/python3.9/site-packages/style50/__init__.py", line 20, in <module>
    from ._api import Style50, StyleCheck, Error
  File "/usr/local/lib/python3.9/site-packages/style50/_api.py", line 18, in <module>
    import magic
  File "/usr/local/lib/python3.9/site-packages/magic.py", line 201, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

**Comment by alexhernandez** [comment]
If you are on Mac and have [Homebrew](https://brew.sh/) installed you can install `libmagic` on your own by running:

`brew install libmagic`

This resolved the issue for me.

If you install `libmagic` via Homebrew you might get another prompt like so:
"style50 requires astyle, but it does not seem to be installed"

You can also resolve this by installing it on your own via Homebrew:

`brew install astyle`

**Comment by tahayparker** [comment]
This error is appearing once again.

`
$ pip install style50
Collecting style50
  Using cached style50-2.7.5-py3-none-any.whl (24 kB)
Collecting python-magic
  Using cached python_magic-0.4.27-py2.py3-none-any.whl (13 kB)
Collecting icdiff
  Using cached icdiff-2.0.5-py3-none-any.whl
Collecting jinja2>=2.10
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting termcolor
  Using cached termcolor-2.0.1-py3-none-any.whl (5.4 kB)
Collecting jsbeautifier
  Using cached jsbeautifier-1.14.6-py3-none-any.whl
Collecting autopep8>=1.4.3
  Using cached autopep8-1.7.0-py2.py3-none-any.whl (45 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting pycodestyle>=2.9.1
  Using cached pycodestyle-2.9.1-py2.py3-none-any.whl (41 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting editorconfig>=0.12.2
  Using cached EditorConfig-0.12.3-py3-none-any.whl (16 kB)
Collecting six>=1.13.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: icdiff, editorconfig, argparse, toml, termcolor, six, python-magic, pycodestyle, MarkupSafe, jsbeautifier, jinja2, autopep8, style50
Successfully installed MarkupSafe-2.1.1 argparse-1.4.0 autopep8-1.7.0 editorconfig-0.12.3 icdiff-2.0.5 jinja2-3.1.2 jsbeautifier-1.14.6 pycodestyle-2.9.1 python-magic-0.4.27 six-1.16.0 style50-2.7.5 termcolor-2.0.1 toml-0.10.2
$ style50
Traceback (most recent call last):
  File "/usr/local/python/current/bin/style50", line 5, in <module>
    from style50.__main__ import main
  File "/usr/local/python/3.10.7/lib/python3.10/site-packages/style50/__init__.py", line 20, in <module>
    from ._api import Style50, StyleCheck, Error
  File "/usr/local/python/3.10.7/lib/python3.10/site-packages/style50/_api.py", line 18, in <module>
    import magic
  File "/usr/local/python/3.10.7/lib/python3.10/site-packages/magic/__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
  File "/usr/local/python/3.10.7/lib/python3.10/site-packages/magic/loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
`

I have tried installing python-magic and tried it with every version available, but nothing works.

**Comment by rongxin-liu** [comment]
> ImportError: failed to find libmagic. Check your installation

You might want to checkout this issue:
https://github.com/Yelp/elastalert/issues/1927

Basically,

`brew install libmagic`

**Comment by rongxin-liu** [comment]
In summary, if having issues running `style50` on macOS, please make sure `astyle` and `libmagic` are installed on macOS.

They could be installed via [Homebrew](https://brew.sh/):

`brew install astyle`
`brew install libmagic`

**Comment by tahayparker** [comment]
I'm running a GitHub Codespace and even after install brew, style50 throws the same error
Edit: Codespace is running Ubuntu 22.04 LTS

**Comment by rongxin-liu** [comment]
Are you using CS50 Codespace on code.cs50.io? Could you please send us a screenshot of the issue? style50 should run on our Codespace without issues.

**Comment by tahayparker** [comment]
No, it's not a CS50 codespace, it's on a personal codespace
![image](https://user-images.githubusercontent.com/98612931/192004189-5ed399ae-5b51-410a-a501-c5f30a53c218.png)

**Comment by rongxin-liu** [comment]
Well in this case you would need to install `libmagic` on Ubuntu:
`sudo apt-get install libmagic1`

**Comment by tahayparker** [comment]
It works!
Thank you very much!
