### ISSUE TITLE
Using mode score seems to crash

### ISSUE THREAD

**Issue by occ-computer-science** [cs50/style50#95]
This command line works OK.
```
style50 -o unified h05.cpp
```
While this crashes.
```
style50 -o score h05.cpp
Sorry, something's wrong! Let sysadmins@cs50.harvard.edu know!
Traceback (most recent call last):
  File "/usr/local/bin/style50", line 11, in <module>
    load_entry_point('style50==2.7.3', 'console_scripts', 'style50')()
  File "/usr/local/lib/python3.7/site-packages/style50/__main__.py", line 49, in main
    Style50(args.output).run(args.file, ignore=ignore)
  File "/usr/local/lib/python3.7/site-packages/style50/_api.py", line 105, in run
    print(render(**results))
  File "/usr/local/lib/python3.7/site-packages/style50/renderer/_renderers.py", line 62, in to_ansi_score
    return "\n".join(lines)
TypeError: sequence item 0: expected str instance, float found
```

**Comment by occ-computer-science** [comment]
Thank you. I had gone ahead and made a local copy for my students and fixed this. (It also let me change the rules, somewhat). When the fix is submitted, how long does it take for it to appear in the student's copy of CS50 IDE (since we no longer manually update)?
